### ISSUE TITLE
Sugestão de melhoria para seu código

### ISSUE THREAD

**Issue by dudabecker** [alanissima/eh-o-amoooor#1]
Seu site apresenta um botão para que eu possa escutar a música mas ele não leva a lugar nenhum, seria interessante se o usuário fosse direcionado a um vídeo do youtube quando esse botão fosse clicado.

**Comment by Mariaehsb** [comment]
> Seu site apresenta um botão para que eu possa escutar a música mas ele não leva a lugar nenhum, seria interessante se o usuário fosse direcionado a um vídeo do youtube quando esse botão fosse clicado. 

O problema já foi resolvido.

373911270b6573ece23412f4150d6b28e6646f71
